MONGODB_HOST: 23.20.91.149
REDIS_HOST: 54.82.23.74
CATALOGUE_HOST: 13.220.56.116
CART_HOST: 54.90.192.54
USER_HOST: 13.221.95.40
RABBITMQ_HOST: 98.84.57.35
MYSQL_HOST: 54.91.140.179
SHIPPING_HOST: 34.228.10.49
PAYMENT_HOST: 100.27.198.199